### PR TITLE
removed gazebo_driver and gazebo_odom

### PR DESCRIPTION
**Pull request by mmaao**

### CODE REVIEW

**Review by kruusamae — APPROVED** [review]
look good.

**Comment by kruusamae** [comment]
@Veix123 kas siin on nüüd ka mingi org->com kala?

**Comment by kruusamae** [comment]
@mmaao vaata üle, kas kusagil on mingi tarvise org->com kala?

**Comment by Veix123** [comment]
> @mmaao vaata üle, kas kusagil on mingi tarvise org->com kala?

jah

**Pull request merged**
